name: 'C++ Style Check'
description: 'Runs C++ style check with Uncrustify'
author: 'coleaeason'
inputs: 
  configPath:
    description: 'Alternate configuration file to use'
    required: false
  defaultBranch:
    description: 'Alternative default branch name, default is master'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
    icon: 'edit-3'
    color: 'green'
